04-14 09:00:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:19 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:20 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 09:00:20 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:00:20 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool%3A+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 09:00:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:00:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 09:00:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:00:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 09:00:54 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4872a90>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 09:00:54 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-14 09:00:54 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:00:54 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:00:54 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:54 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:55 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:00:55 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:55 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:56 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:56 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:57 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:57 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:00:57 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:00:57 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:00:57 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:00:59 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:00:59 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 09:00:59 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:01:29 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4b2d430>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 09:01:29 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-14 09:01:29 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:01:29 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:01:29 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:29 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:29 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:01:29 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:30 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:31 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:31 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:32 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:01:32 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:01:32 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-14 09:01:32 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:01:33 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:01:34 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:01:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 09:01:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:02:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb48ada70>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 09:02:04 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-14 09:02:04 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:02:04 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:02:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:04 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:02:04 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:02:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:05 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:06 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:07 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:07 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:02:07 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:02:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:02:09 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-14 09:02:09 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:02:09 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:02:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:09 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:09 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:02:09 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:02:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:13 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-14 09:02:13 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:02:13 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:02:14 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-14 09:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:02:14 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:14 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:15 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:02:15 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-14 09:02:18 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:02:18 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:19 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-14 09:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:02:19 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:19 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:20 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:02:20 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:20 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:22 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 09:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:22 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 09:02:23 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 09:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 09:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:02:25 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-14 09:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 09:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-14 09:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:25 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 09:02:25 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 09:02:26 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 09:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:28 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=joker+2019%20seed%20%3E%200, data: [][0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-14 09:02:28 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 09:02:29 INFO [0m[core.media.movie.searcher] Wrong: MP3-daily-2019-January-16-Pop, undetermined naming. Looking for 'Joker (2019)'[0m
04-14 09:02:29 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 09:02:29 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 12:58:00 INFO [0m[core.media.movie.searcher] Search for Ad Astra in Screener[0m
04-14 12:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 12:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2935510&internal=False, data: [][0m
04-14 12:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:00 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:01 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 12:58:01 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 12:58:01 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 12:58:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:01 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/, data: [][0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201, data: [][0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=ad+astra+2019%20seed%20%3E%200, data: [][0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2935510/, data: [][0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 12:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1, data: [][0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in ThePirateBay: https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='pirateproxy.lat', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.magnetdl.com', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in KickAssTorrents: http://katcr.to/span/m-i2935510/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='katcr.to', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Torrentz: https://torrentz2.eu/feed?f=ad+astra+2019%20seed%20%3E%200 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentz2.eu', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Rarbg: https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentapi.org', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='yts.am', port=443): Read timed out. (read timeout=30)
[0m
04-14 12:58:33 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2935510&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 12:58:33 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 12:58:33 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 12:58:33 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 12:58:33 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2935510&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 12:58:33 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2935510&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 12:59:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4803bd0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 12:59:04 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-14 12:59:04 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 12:59:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-14 12:59:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:05 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 12:59:05 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 12:59:05 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 12:59:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:05 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:06 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:07 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-14 12:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=joker+2019%20seed%20%3E%200, data: [][0m
04-14 12:59:08 INFO [0m[core.media.movie.searcher] Wrong: MP3-daily-2019-January-16-Pop, undetermined naming. Looking for 'Joker (2019)'[0m
04-14 12:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 12:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 12:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 12:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 12:59:40 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb480daf0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 12:59:40 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 720p[0m
04-14 12:59:40 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 12:59:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-14 12:59:40 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:40 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:41 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:41 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:41 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 12:59:41 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 12:59:41 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 12:59:42 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:42 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:43 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 12:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-14 12:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 12:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool%3A+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 12:59:44 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 12:59:44 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 12:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 12:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 12:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 12:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 13:00:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4930fb0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 13:00:15 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-14 13:00:15 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:00:15 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:00:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:18 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:00:18 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:19 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:00:19 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:00:19 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 13:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:00:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb48d0ab0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 13:00:50 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-14 13:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:00:50 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:51 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:00:51 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:00:51 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:51 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:52 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:52 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:53 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-14 13:00:54 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:00:54 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 13:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:01:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb48dd4f0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 13:01:25 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-14 13:01:25 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:01:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:25 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:01:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:25 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:01:25 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:28 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:01:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:01:28 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:01:28 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 13:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:02:00 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb6029a30>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 13:02:00 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-14 13:02:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:02:00 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:02:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:00 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:00 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:02:00 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:01 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-14 13:02:03 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:02:03 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:02:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:05 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:02:05 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-14 13:02:05 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:02:05 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:02:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:05 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:05 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:02:05 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:06 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:07 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:08 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:08 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-14 13:02:09 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:02:09 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:02:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:10 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-14 13:02:10 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:02:10 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:02:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:10 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:02:10 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 13:02:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:13 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 13:02:13 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 13:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 13:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:02:15 INFO [0m[core.media.movie.searcher] Search for Midsommar in Screener[0m
04-14 13:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt8772262&internal=False, data: [][0m
04-14 13:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:16 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:02:16 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:17 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=midsommar+2019%20seed%20%3E%200, data: [][0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Midsommar+2019%22/0/7/201, data: [][0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt8772262&limit=10&page=1, data: [][0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/m/midsommar-2019/se/desc/1/, data: [][0m
04-14 13:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i8772262/, data: [][0m
04-14 13:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt8772262&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 13:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 13:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=8772262&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 13:02:22 INFO [0m[core.media.movie.searcher] Search for John Wick: Chapter 3 – Parabellum in Screener[0m
04-14 13:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 13:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6146586&internal=False, data: [][0m
04-14 13:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:22 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:22 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 13:02:22 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 13:02:22 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 13:02:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:23 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:24 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-parabellum-2019/se/desc/1/, data: [][0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6146586/, data: [][0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick+chapter+3+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019%22/0/7/201, data: [][0m
04-14 13:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6146586&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 13:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick%3A+chapter+3+%E2%80%93+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 13:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/, data: [][0m
04-14 13:02:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/ Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/
[0m
04-14 13:02:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6146586&limit=10&page=1, data: [][0m
04-14 13:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6146586&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 13:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6146586&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 15:32:49 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.couchpota.to/messages/?last_check=1384713000, data: [][0m
04-14 16:58:00 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 720p[0m
04-14 16:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 16:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-14 16:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:01 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 16:58:01 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 16:58:01 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 16:58:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:14 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 16:58:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 16:58:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Torrentz: https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentz2.eu', port=443): Read timed out. (read timeout=30)
[0m
04-14 16:58:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in ThePirateBay: https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='pirateproxy.lat', port=443): Read timed out. (read timeout=30)
[0m
04-14 16:58:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.magnetdl.com', port=443): Read timed out. (read timeout=30)
[0m
04-14 16:58:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool%3A+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 16:58:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:58:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Rarbg: https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentapi.org', port=443): Read timed out. (read timeout=30)
[0m
04-14 16:58:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='yts.am', port=443): Read timed out. (read timeout=30)
[0m
04-14 16:58:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 16:58:45 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 16:58:45 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 16:58:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 16:58:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 16:58:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 16:59:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4454bd0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 16:59:15 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-14 16:59:15 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 16:59:15 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 16:59:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:16 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 16:59:16 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 16:59:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:59:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 16:59:19 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 16:59:19 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 16:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 16:59:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 16:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4400890>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 16:59:50 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-14 16:59:50 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 16:59:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:50 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 16:59:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:50 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 16:59:50 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 16:59:51 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:51 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:52 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:52 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:53 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 16:59:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:59:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-14 16:59:53 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 16:59:53 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 16:59:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 16:59:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 16:59:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:00:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4400210>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 17:00:25 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-14 17:00:26 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:00:26 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:00:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:26 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:00:26 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:00:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:28 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:29 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:29 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:00:29 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:00:29 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 17:00:29 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 17:00:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:00:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 17:00:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:01:01 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb42c3eb0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 17:01:01 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-14 17:01:01 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:01:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:01 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:01:01 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:01 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:01:01 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:01:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:01:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-14 17:01:04 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 17:01:04 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 17:01:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:01:06 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 17:01:06 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:01:36 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4834e50>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 17:01:36 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-14 17:01:36 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:01:36 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:01:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:36 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:36 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:01:36 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:01:37 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:37 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:38 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:38 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:39 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:39 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:01:39 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-14 17:01:39 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:01:39 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 17:01:39 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 17:01:40 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:01:40 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 17:02:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4818eb0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 17:02:10 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-14 17:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:11 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:02:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:11 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:02:11 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:02:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:14 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 17:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:02:14 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 17:02:14 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 17:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 17:02:15 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:02:16 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-14 17:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-14 17:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:16 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:02:16 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:02:17 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:19 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=joker+2019%20seed%20%3E%200, data: [][0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-14 17:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 17:02:20 INFO [0m[core.media.movie.searcher] Wrong: MP3-daily-2019-January-16-Pop, undetermined naming. Looking for 'Joker (2019)'[0m
04-14 17:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 17:02:22 INFO [0m[core.media.movie.searcher] Search for John Wick: Chapter 3 – Parabellum in Screener[0m
04-14 17:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6146586&internal=False, data: [][0m
04-14 17:02:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:23 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:23 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:02:23 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:02:23 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:24 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-parabellum-2019/se/desc/1/, data: [][0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019%22/0/7/201, data: [][0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick+chapter+3+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6146586/, data: [][0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6146586&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 17:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick%3A+chapter+3+%E2%80%93+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 17:02:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/, data: [][0m
04-14 17:02:27 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/ Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/
[0m
04-14 17:02:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6146586&limit=10&page=1, data: [][0m
04-14 17:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6146586&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:02:31 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6146586&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 17:02:33 INFO [0m[core.media.movie.searcher] Search for Ad Astra in Screener[0m
04-14 17:02:33 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:02:33 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2935510&internal=False, data: [][0m
04-14 17:02:33 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:33 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:33 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:02:33 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:02:33 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:02:34 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:35 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:35 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:36 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=ad+astra+2019%20seed%20%3E%200, data: [][0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201, data: [][0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/, data: [][0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2935510/, data: [][0m
04-14 17:02:36 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2935510&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 17:02:36 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 17:02:36 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 17:02:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1, data: [][0m
04-14 17:02:42 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2935510&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 17:02:42 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2935510&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:02:43 INFO [0m[core.media.movie.searcher] Search for Midsommar in Screener[0m
04-14 17:02:43 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 17:02:43 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt8772262&internal=False, data: [][0m
04-14 17:02:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:44 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 17:02:44 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 17:02:44 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 17:02:45 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:45 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:46 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:46 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:47 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=midsommar+2019%20seed%20%3E%200, data: [][0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Midsommar+2019%22/0/7/201, data: [][0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/m/midsommar-2019/se/desc/1/, data: [][0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i8772262/, data: [][0m
04-14 17:02:47 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt8772262&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 17:02:52 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt8772262&limit=10&page=1, data: [][0m
04-14 17:02:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 17:02:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=8772262&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 20:58:00 INFO [0m[core.media.movie.searcher] Search for Ad Astra in Screener[0m
04-14 20:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 20:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt2935510&internal=False, data: [][0m
04-14 20:58:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:01 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 20:58:01 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 20:58:01 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 20:58:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt2935510&search=Ad+Astra+2019&user=&passkey=xxx&search=Ad+Astra+2019&user=&passkey=xxx[0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=ad+astra+2019%20seed%20%3E%200, data: [][0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201, data: [][0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i2935510/, data: [][0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/, data: [][0m
04-14 20:58:04 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1, data: [][0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in ThePirateBay: https://pirateproxy.cat/search/%22Ad+Astra+2019%22/0/7/201 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='pirateproxy.lat', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Torrentz: https://torrentz2.eu/feed?f=ad+astra+2019%20seed%20%3E%200 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentz2.eu', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/a/ad-astra-2019/se/desc/1/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='www.magnetdl.com', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt2935510&limit=10&page=1 Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='yts.am', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Rarbg: https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='torrentapi.org', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 ERROR [31m[hpotato.core.plugins.base] Failed opening url in KickAssTorrents: http://katcr.to/span/m-i2935510/ Traceback (most recent call last):
ReadTimeout: HTTPSConnectionPool(host='katcr.to', port=443): Read timed out. (read timeout=30)
[0m
04-14 20:58:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt2935510&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 20:58:34 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 20:58:34 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 20:58:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 20:58:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt2935510&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 20:58:34 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=2935510&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 20:59:04 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Ad+Astra+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4818c50>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 20:59:04 INFO [0m[core.media.movie.searcher] Search for John Wick: Chapter 3 – Parabellum in Screener[0m
04-14 20:59:05 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 20:59:05 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6146586&internal=False, data: [][0m
04-14 20:59:05 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:05 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:06 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 20:59:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:06 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:06 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 20:59:06 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 20:59:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:07 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:08 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6146586&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx&search=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&user=&passkey=xxx[0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?get_token=get_token&app_id=couchpotato, data: [][0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-parabellum-2019/se/desc/1/, data: [][0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019%22/0/7/201, data: [][0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick+chapter+3+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6146586&limit=10&page=1, data: [][0m
04-14 20:59:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6146586/, data: [][0m
04-14 20:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=john+wick%3A+chapter+3+%E2%80%93+parabellum+2019%20seed%20%3E%200, data: [][0m
04-14 20:59:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/, data: [][0m
04-14 20:59:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in MagnetDL: http://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/ Traceback (most recent call last):
HTTPError: 404 Client Error: Not Found for url: https://www.magnetdl.com/j/john-wick-chapter-3-%E2%80%93-parabellum-2019/se/desc/1/
[0m
04-14 20:59:10 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6146586&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 20:59:10 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 20:59:10 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6146586&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 20:59:10 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6146586&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 20:59:41 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=John+Wick%3A+Chapter+3+%E2%80%93+Parabellum+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4b2d230>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 20:59:41 INFO [0m[core.media.movie.searcher] Search for Midsommar in Screener[0m
04-14 20:59:41 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 20:59:41 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt8772262&internal=False, data: [][0m
04-14 20:59:41 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:41 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:41 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 20:59:41 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 20:59:42 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 20:59:42 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:42 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:43 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:43 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:44 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt8772262&search=Midsommar+2019&user=&passkey=xxx&search=Midsommar+2019&user=&passkey=xxx[0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/m/midsommar-2019/se/desc/1/, data: [][0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=midsommar+2019%20seed%20%3E%200, data: [][0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i8772262/, data: [][0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Midsommar+2019%22/0/7/201, data: [][0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt8772262&limit=10&page=1, data: [][0m
04-14 20:59:44 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt8772262&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 20:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Midsommar+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 20:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt8772262&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 20:59:45 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=8772262&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 21:00:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Midsommar+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Midsommar+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4a69310>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 21:00:15 INFO [0m[core.media.movie.searcher] Search for Joker in Screener[0m
04-14 21:00:15 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:00:15 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt7286456&internal=False, data: [][0m
04-14 21:00:15 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:15 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:15 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:00:16 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:00:16 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:00:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:16 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt7286456&search=Joker+2019&user=&passkey=xxx&search=Joker+2019&user=&passkey=xxx[0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/j/joker-2019/se/desc/1/, data: [][0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Joker+2019%22/0/7/201, data: [][0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt7286456&limit=10&page=1, data: [][0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=joker+2019%20seed%20%3E%200, data: [][0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i7286456/, data: [][0m
04-14 21:00:18 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt7286456&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 21:00:20 INFO [0m[core.media.movie.searcher] Wrong: MP3-daily-2019-January-16-Pop, undetermined naming. Looking for 'Joker (2019)'[0m
04-14 21:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 21:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=7286456&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 21:00:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt7286456&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:00:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Joker+2019&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb485ba30>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 21:00:50 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 720p[0m
04-14 21:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: get https://hd4free.xyz/searchapi.php?apikey=&username=&imdbid=tt6612630&internal=False, data: [][0m
04-14 21:00:50 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:50 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:50 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:00:50 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:00:51 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:00:51 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:51 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:52 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:52 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:53 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/207, data: [][0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get http://katcr.to/span/m-i6612630/, data: [][0m
04-14 21:00:53 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentapi.org/pubapi_v2.php?token=g6p03ekams&mode=search&search_imdb=tt6612630&min_seeders=10&min_leechers=0&ranked=1&category=movies&format=json_extended&app_id=couchpotato, data: [][0m
04-14 21:00:54 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:00:54 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:00:54 INFO [0m[hpotato.core.plugins.base] Opening url: get https://torrentz2.eu/feed?f=deadpool%3A+no+good+deed+2017%20seed%20%3E%200, data: [][0m
04-14 21:00:54 ERROR [31m[hpotato.core.plugins.base] Failed opening url in Yts: https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1 Traceback (most recent call last):
HTTPError: 520 Server Error: Origin Error for url: https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1
[0m
04-14 21:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 21:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=3000&adv_age=1500&max=400&xmaxsize=10000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:00:55 INFO [0m[hpotato.core.plugins.base] Opening url: get https://api.nzbgeek.info/api?imdbid=6612630&apikey=xxx&t=movie&extended=1&cat=2000, data: [][0m
04-14 21:01:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb45beff0>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 21:01:25 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in 1080p[0m
04-14 21:01:25 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:01:25 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:01:25 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:25 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:26 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:01:26 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:01:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:26 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:27 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:28 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:28 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:28 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:01:29 INFO [0m[hpotato.core.plugins.base] Opening url: get https://yts.am/api/v2/list_movies.json?query_term=tt6612630&limit=10&page=1, data: [][0m
04-14 21:01:29 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:01:29 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:01:29 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5, data: [][0m
04-14 21:01:30 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=4000&adv_age=1500&max=400&xmaxsize=20000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:02:00 ERROR [31m[hpotato.core.plugins.base] Failed opening url in NZBClub: https://www.nzbclub.com/nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 Traceback (most recent call last):
ConnectTimeout: HTTPSConnectionPool(host='www.nzbclub.com', port=443): Max retries exceeded with url: /nzbrss.aspx?q=Deadpool%3A+No+Good+Deed+2017&rpp=200&sp=1&ns=1&ig=1&st=5 (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0xb4805e10>, 'Connection to www.nzbclub.com timed out. (connect timeout=30)'))
[0m
04-14 21:02:00 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Rip[0m
04-14 21:02:00 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:02:00 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:02:00 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:00 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:00 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:02:00 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:02:01 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:01 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:02 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:02 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:03 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:03 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201,207, data: [][0m
04-14 21:02:04 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:02:04 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=700&adv_age=1500&max=400&xmaxsize=7000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:02:06 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in BR-Disk[0m
04-14 21:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:02:06 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:02:06 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:07 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:07 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:02:07 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:02:07 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:08 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:08 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:09 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:09 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:10 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:10 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:10 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:02:10 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=20000&adv_age=1500&max=400&xmaxsize=60000&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:02:11 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-Rip[0m
04-14 21:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:02:11 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:02:11 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:11 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:12 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:02:12 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:02:12 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:12 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:13 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:13 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:14 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:14 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/201, data: [][0m
04-14 21:02:15 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:02:15 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:16 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=2400&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 21:02:17 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in DVD-R[0m
04-14 21:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:02:17 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:02:17 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:17 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:17 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:02:17 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:02:18 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:18 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:19 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:19 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:20 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:20 INFO [0m[hpotato.core.plugins.base] Opening url: get https://pirateproxy.cat/search/%22Deadpool%3A+No+Good+Deed+2017%22/0/7/202, data: [][0m
04-14 21:02:20 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:02:20 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:02:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:21 INFO [0m[core.media.movie.searcher] Search for Deadpool: No Good Deed in Screener[0m
04-14 21:02:21 INFO [0m[hpotato.core.plugins.base] Opening url: post https://www.sceneaccess.eu/login, data: ['username', 'password', 'submit'][0m
04-14 21:02:21 ERROR [31m[edia._base.providers.base] Failed to parsing HD4Free: Traceback (most recent call last):
  File "/app/couchpotato/couchpotato/core/media/_base/providers/base.py", line 84, in getJsonData
    return json.loads(data)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
[0m
04-14 21:02:21 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:21 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/1337x/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:22 ERROR [31m[edia._base.providers.base] Failed to login SceneAccess: unknown[0m
04-14 21:02:22 ERROR [31m[edia._base.providers.base] Failed to login to: SceneAccess[0m
04-14 21:02:22 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:22 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/btbit/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:23 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:23 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/extratorrent-ag/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:24 ERROR [31m[hpotato.core.plugins.base] Failed opening url in TorrentPotato: http://10.0.0.12:9117/api/v2.0/indexers/gimmepeers/results/potato/?imdbid=tt6612630&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx&search=Deadpool%3A+No+Good+Deed+2017&user=&passkey=xxx[0m
04-14 21:02:24 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:25 ERROR [31mFailed encoding stuff to log "Cant find imdb in database. Are you sure this imdb exists?": not all arguments converted during string formatting[0m
04-14 21:02:25 ERROR [31m[e.providers.torrent.rarbg] Cant find imdb in database. Are you sure this imdb exists?[0m
04-14 21:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get http://www.magnetdl.com/d/deadpool-no-good-deed-2017/se/desc/1/, data: [][0m
04-14 21:02:26 INFO [0m[hpotato.core.plugins.base] Opening url: get https://www.binsearch.info/index.php?q=tt6612630&adv_nfo=on&xminsize=600&adv_age=1500&max=400&xmaxsize=1600&m=n&adv_sort=date&adv_col=on, data: [][0m
04-14 22:39:58 INFO [0m[chpotato.core._base._core] Shutting down[0m
